version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: subweb-mysql
    restart: always
    environment:
      MYSQL_DATABASE: subweb
      MYSQL_ROOT_PASSWORD: ***
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 5

  backend:
    volumes:
      - ./SubWeb/genre:/app/genre
    build: ./backend
    container_name: subweb-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/subweb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ***
      SPRING_DATASOURCE_PASSWORD: ***
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: subweb-frontend
    restart: "no"
    depends_on:
      - backend
    volumes:
      - frontend-build:/output
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine  # 특정 버전 지정
    container_name: subweb-nginx
    ports:
      - "80:80"  # HTTP 포트 추가
      - "443:443"
    volumes:
      - ./SubWeb/genre:/app/genre
      - frontend-build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/localhost.pem:/etc/ssl/certs/localhost.pem
      - ./nginx/localhost-key.pem:/etc/ssl/private/localhost-key.pem
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mysql-data:
  frontend-build:

networks:
  app-network:  # 전용 네트워크 생성
    driver: bridge
